# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mybackend:
    image: mybackend
    build:
      context: .
      dockerfile: MyBackEnd/Dockerfile
    ports:
      - 5273:5273
  
  mybackend-dapr: 
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "MyBackEnd", "-app-port", "80" ]
    depends_on: 
        - mybackend
    network_mode: "service:mybackend"

  myfrontend:
    image: myfrontend
    build:
      context: .
      dockerfile: MyFrontEnd/Dockerfile
    ports:
      - 5274:5274
  
  myfrontend-dapr:
     image: "daprio/daprd:latest"
     command: [ "./daprd", "-app-id", "MyFrontEnd", "-app-port", "80" ]
     depends_on: 
        - myfrontend
     network_mode: "service:myfrontend"
