# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mybackend:
    image: mybackend
    build:
      context: .
      dockerfile: MyBackEnd/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5273:5273
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
